### PR TITLE
New status command format

### LINKED ISSUE #340: More human-friendly output of rabbitmqctl status
`rabbitmqctl status` should use a more human-friendly format, similar to the new `rabbitmq-diagnostics` commands (#292).

### PR DESCRIPTION
**Pull request by michaelklishin**
Depends on https://github.com/rabbitmq/rabbitmq-server/pull/1977.

Closes #340.

To try it out:

```
gmake; ./escript/rabbitmqctl status --silent
```

To try JSON formatting:

```
gmake; ./escript/rabbitmqctl status --formatter=json | jq
```

### CODE REVIEW

**Comment by michaelklishin** [comment]
We decided to add log and config file paths, bring back the list of running applications.

**Comment by gerhard** [comment]
This is looking very nice, loving it!

A few suggestions:

* Move `OS`, `System PID` & `Uptime` under **Runtime**
* `OS: macOS` instead of `OS: MacOS`
* `Erlang configuration: ...` instead of `Erlang info info`
* `Erlang processes: 433 used, 1048576 limit`
* `Erlang run queue` instead of `Run queue`
* `Cluster heartbeat timeout` instead of `Net tick timeout`
* Format `Disk Space` values into MBs - ideally both memory & disk space values would be human-friendly (KB/MB/GB etc.)
* I would show global counters: vhosts, queues, channels & conns
* I would list plugins enabled - applications feel too verbose IMO
* I would display nodename & possibly other nodes in the cluster

**Comment by michaelklishin** [comment]
Other nodes are displayed in `cluster_status`. Counting channels is currently not as trivial as it sounds as we have to ask every connection which can be very expensive.

Everything except for units is done.

**Comment by michaelklishin** [comment]
Ready for another round.

**Comment by gerhard** [comment]
This is so much better now! The detail is spot-on - the only thing that I'm missing in this output is cluster info. Happy to leave it for another time.

Any chance we could rename `gb` to `G`? `G` is more popular in utilities such as top, htop, dstat, ls, etc. It's also the [SI for `giga`, `1000^3`](https://en.wikipedia.org/wiki/Binary_prefix).

What are your thoughts on this ordering & formatting?

```
RABBITMQ
  Version: 3.8.0+beta.3.37.g2152070
  Node name: rabbit@focker
  Cluster name: rabbit@focker
  Connections: 0
  Queues: 0
  Virtual hosts: 1
  Enabled plugins:
  - rabbitmq_management
  - rabbitmq_web_dispatch
  - rabbitmq_management_agent
  - amqp_client
  - cowboy
  - cowlib
  Enabled plugins file: /var/folders/d6/dt_lc3pn5qg8wd93w_tgmx7c0000gn/T/rabbitmq-test-instances/rabbit/enabled_plugins
  Config: /var/folders/d6/dt_lc3pn5qg8wd93w_tgmx7c0000gn/T/rabbitmq-test-instances/test.config
  Data directory: /var/folders/d6/dt_lc3pn5qg8wd93w_tgmx7c0000gn/T/rabbitmq-test-instances/rabbit/mnesia/rabbit
  Log files:
  - /var/folders/d6/dt_lc3pn5qg8wd93w_tgmx7c0000gn/T/rabbitmq-test-instances/rabbit/log/rabbit.log
  - /var/folders/d6/dt_lc3pn5qg8wd93w_tgmx7c0000gn/T/rabbitmq-test-instances/rabbit/log/rabbit_upgrade.log

ERLANG
  Version: Erlang/OTP 21 [erts-10.3.2] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:320] [hipe] [dtrace]
  Processes used: 434
  Processes limit: 1048576
  Scheduler run queue: 1
  Uptime (seconds): 2055
  Low free disk space watermark: 0.05G
  Free disk space: 755.16G
  Memory:
    Calculation strategy: rss
    High watermark: 0.4 (10.99G)
    Limit: 27.48G
    other_system: 0.03G (25.37 %)
    allocated_unused: 0.03G (24.91 %)
    code: 0.02G (22.71 %)
    other_proc: 0.02G (20.28 %)
    other_ets: 0.00G (3.13 %)
    plugins: 0.00G (1.92 %)
    atom: 0.00G (1.11 %)
    metrics: 0.00G (0.19 %)
    mgmt_db: 0.00G (0.17 %)
    binary: 0.00G (0.11 %)
    mnesia: 0.00G (0.07 %)
    msg_index: 0.00G (0.03 %)
    connection_other: 0.00G (0.0 %)
    connection_channels: 0.00G (0.0 %)
    connection_readers: 0.00G (0.0 %)
    connection_writers: 0.00G (0.0 %)
    queue_procs: 0.00G (0.0 %)
    queue_slave_procs: 0.00G (0.0 %)
    quorum_queue_procs: 0.00G (0.0 %)
    reserved_unallocated: 0.00G (0.0 %)

OS
  Platform: macOS
  PID: 6030
  Files used: 2
  Files limit: 7068
  Sockets used: 0
  Sockets limit: 6359
  Socket listeners:
  - Interface: [::], port: 25672, protocol: clustering, purpose: inter-node and CLI tool communication
  - Interface: [::], port: 5672, protocol: amqp, purpose: AMQP 0-9-1 and AMQP 1.0
  - Interface: [::], port: 15672, protocol: http, purpose: HTTP API
```

This was my starting point:

```
Runtime

OS PID: 6030
OS: macOS
Uptime (seconds): 2055
RabbitMQ version: 3.8.0+beta.3.37.g2152070
Node name: rabbit@focker
Erlang configuration: Erlang/OTP 21 [erts-10.3.2] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:320] [hipe] [dtrace]
Erlang processes: 434 used, 1048576 limit
Scheduler run queue: 1
Cluster heartbeat timeout (net_ticktime): 60

Plugins

Enabled plugin file: /var/folders/d6/dt_lc3pn5qg8wd93w_tgmx7c0000gn/T/rabbitmq-test-instances/rabbit/enabled_plugins
Enabled plugins:

 * rabbitmq_management
 * rabbitmq_web_dispatch
 * rabbitmq_management_agent
 * amqp_client
 * cowboy
 * cowlib

Data directory

Node data directory: /var/folders/d6/dt_lc3pn5qg8wd93w_tgmx7c0000gn/T/rabbitmq-test-instances/rabbit/mnesia/rabbit

Config files

 * /var/folders/d6/dt_lc3pn5qg8wd93w_tgmx7c0000gn/T/rabbitmq-test-instances/test.config

Log file(s)

 * /var/folders/d6/dt_lc3pn5qg8wd93w_tgmx7c0000gn/T/rabbitmq-test-instances/rabbit/log/rabbit.log
 * /var/folders/d6/dt_lc3pn5qg8wd93w_tgmx7c0000gn/T/rabbitmq-test-instances/rabbit/log/rabbit_upgrade.log

Alarms

(none)

Memory

Calculation strategy: rss
Memory high watermark: 0.4, limit: 27.4878 gb
other_system: 0.0278 gb (25.37 %)
allocated_unused: 0.0273 gb (24.91 %)
code: 0.0249 gb (22.71 %)
other_proc: 0.0222 gb (20.28 %)
other_ets: 0.0034 gb (3.13 %)
plugins: 0.0021 gb (1.92 %)
atom: 0.0012 gb (1.11 %)
metrics: 0.0002 gb (0.19 %)
mgmt_db: 0.0002 gb (0.17 %)
binary: 0.0001 gb (0.11 %)
mnesia: 0.0001 gb (0.07 %)
msg_index: 0.0 gb (0.03 %)
connection_other: 0.0 gb (0.0 %)
connection_channels: 0.0 gb (0.0 %)
connection_readers: 0.0 gb (0.0 %)
connection_writers: 0.0 gb (0.0 %)
queue_procs: 0.0 gb (0.0 %)
queue_slave_procs: 0.0 gb (0.0 %)
quorum_queue_procs: 0.0 gb (0.0 %)
reserved_unallocated: 0.0 gb (0.0 %)

File Descriptors

Total: 2, limit: 7068
Sockets: 0, limit: 6359

Free Disk Space

Low free disk space watermark: 0.05 gb
Free disk space: 755.1609 gb

Totals

Connection count: 0
Queue count: 0
Virtual host count: 1

Listeners

Interface: [::], port: 25672, protocol: clustering, purpose: inter-node and CLI tool communication
Interface: [::], port: 5672, protocol: amqp, purpose: AMQP 0-9-1 and AMQP 1.0
Interface: [::], port: 15672, protocol: http, purpose: HTTP API
```

**Comment by michaelklishin** [comment]
We have been using `kb`, `mb` and `gb` since 3.7.0 (in `memory_breakdown`). We can add more units at any point but I think what we have is reasonable.

As is said earlier, cluster nodes do not belong to `status`. There is `cluster_status` and has been since 2010 or so. The goal is not to make this a one stop command. `report` already includes `status` and a ton of other information, for example.

**Comment by michaelklishin** [comment]
I think we can merge this and see what `beta.4` users say next month.

**Pull request merged**
