### PR TITLE
Document --no-table-headers

### LINKED ISSUE #274: Create help and short command alias for "--no-table-headers"
See #264, #273 and https://github.com/rabbitmq/rabbitmq-website/issues/633.

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #274

Adds `-s` / `--silent` option too

### CODE REVIEW

**Comment by michaelklishin** [comment]
I like where this is headed 👍

**Comment by michaelklishin** [comment]
To make it more obvious how the `--no-table-headers` gets translated to `table_headers` in the switches, apparently `OptionParser` in Elixir [supports switch negation](https://hexdocs.pm/elixir/OptionParser.html) out of the box.

**Comment by michaelklishin** [comment]
This fails CI on Erlang 19.3 because `string:replace/3` is not available. Looking into it.

**Comment by michaelklishin** [comment]
Something in `OptionParser`'s switch negation function relies on `String.replace/3` which in turn assumes that `string:replace/3` is available in OTP and it isn't in 19.x. Reverted the backport to 3.7.x until after OTP 19.x support is dropped.

**Comment by lukebakken** [comment]
@michaelklishin good catch, that's annoying. We could always see about defining `string:replace/3` if it's missing, depending on how long we expect to support 19.x

**Comment by michaelklishin** [comment]
We already announced that OTP 20 will be the minimum supported version after Jan 1st, 2019.

**Comment by michaelklishin** [comment]
Accidentally discovered another OTP 19-incompatible change introduced recently: https://github.com/rabbitmq/rabbitmq-ct-helpers/commit/9f9d2bd614f43ac6a6e8e6371e20ee9595a97168.

`OptionParser` [does use String.replace/4](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/option_parser.ex#L510) but curiously it still works on OTP 19.x:

``` elixir
Erlang/OTP 19 [erts-8.3.5.4] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [lock-counting]

Interactive Elixir (1.6.6) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> String.replace("abc", "b", "1")
"a1c"
```

**Comment by michaelklishin** [comment]
This has been re-applied with https://github.com/rabbitmq/rabbitmq-ct-helpers/commit/9f9d2bd614f43ac6a6e8e6371e20ee9595a97168 and [Concourse is happy](https://ci.rabbitmq.com/teams/main/pipelines/server-release:v3.7.x/jobs/test-rabbitmq-server%3Act-cluster/builds/162) again.

**Comment by s10** [comment]
I think for backward compatibility you should've kept -q option to work as it worked before and add table headers to the output with --silent flag.
This change completely breaks puppet-rabbitmq module: https://github.com/voxpupuli/puppet-rabbitmq/issues/740

**Comment by lukebakken** [comment]
@s10 there's nothing that can be done for version 3.7.8 as it has shipped.

Please see [this comment](https://github.com/voxpupuli/puppet-rabbitmq/issues/740#issuecomment-440713360) where I outline what versions support what flags. Going forward, the puppet module should use `--quiet --no-table-headers` for maximum compatibility, and have a special case for version 3.7.8 if someone uses it.

**Comment by michaelklishin** [comment]
The lack of table headers was a bug introduced in the 3.7 cycle. We left a couple of suggestions in https://github.com/voxpupuli/puppet-rabbitmq/issues/740.

**Pull request merged**
