### PR TITLE
Add call for IPv6 listening in check_port_connectivity

### PR DESCRIPTION
**Pull request by Gsantomaggio**
## Proposed Changes

Add the inet6 family test. When RabbitMQ is listening in ipv6 the test
fails. This commit tests both ipv4 and ipv6.

Enviroment:
```
sudo lsof -i -P -n | grep LISTEN | grep 5672
beam.smp   4833 gabriele   77u  IPv4 49160038      0t0  TCP *:25672 (LISTEN)
beam.smp   4833 gabriele   90u  IPv6 49158841      0t0  TCP [::1]:5672 (LISTEN)
```
bug:
```
$ scripts/rabbitmq-diagnostics check_port_connectivity

Testing TCP connections to all active listeners on node rabbit@leap ...
Error:
Connection to ports of the following listeners on node rabbit@leap failed:
Interface: [::1], port: 5672, protocol: amqp, purpose: AMQP 0-9-1 and AMQP 1.0
```

with the fix:

```
$ scripts/rabbitmq-diagnostics check_port_connectivity
Testing TCP connections to all active listeners on node rabbit@leap ...
Successfully connected to ports 5672, 25672 on node rabbit@leap.
```

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

I tried to execute the tests on this repostiroy without success:
```
git clone git@github.com:rabbitmq/rabbitmq-cli.git cli
cd cli
make tests
...
...
==> rabbitmqctl
Unchecked dependencies for environment dev:
* rabbit_common (/home/gabriele/git/pivotal/cli/deps/rabbit_common)
  could not find an app file at "_build/dev/lib/rabbit_common/ebin/rabbit_common.app". This may happen if the dependency was not yet compiled, or you specified the wrong application name in your deps, or the dependency indeed has no app file (then you can pass app: false as option)
** (Mix) Can't continue due to errors on dependencies
````
Am I doing the tests in the wrong way?

### CODE REVIEW

**Comment by michaelklishin** [comment]
Looks great, I'll test it in a bit!

**Comment by michaelklishin** [comment]
Tested with a node using the following config:

``` ini
listeners.tcp.1 = ::1:5672
```

Works like a charm 👏

**Comment by michaelklishin** [comment]
Backported to `v3.8.x`, `v3.7.x`.

**Comment by Gsantomaggio** [comment]
Good. :)! 

Last Note: 
I found this bug by deploying https://github.com/rabbitmq/rabbitmq-peer-discovery-k8s/issues/55 and using [command: ["rabbitmq-diagnostics", "check_port_connectivity"]]( https://github.com/rabbitmq/rabbitmq-peer-discovery-k8s/blob/master/examples/k8s_statefulsets/rabbitmq_statefulsets.yaml#L122)  as `readinessProbe`. 

So it can be used starting form the next releases !

**Pull request merged**
