### PR TITLE
Introduce drain/maintenance mode commands

### PR DESCRIPTION
**Pull request by michaelklishin**
A part of rabbitmq/rabbitmq-server#2321 and rabbitmq/rabbitmq-server#2349.

This introduces the following commands most relevant for upgrade and maintenance scenarios:

``` shell
# puts target node into maintenance mode,
# see rabbitmq/rabbitmq-server#2321
rabbitmq-upgrade drain

# puts target node out of maintenance and into regular operating mode,
# see rabbitmq/rabbitmq-server#2321
rabbitmq-upgrade revive

# makes the node no longer accept new client connections
# while not affecting currently established connections
rabbitmqctl suspend_listeners

# makes the node accept client connections again
rabbitmqctl resume_listeners
```

### CODE REVIEW

**Comment by dcorbacho** [comment]
We need a way to discover the current status of a node (maintenance/running). It could be added to the `cluster_status` command

**Comment by michaelklishin** [comment]
@dcorbacho @lukebakken I have added node maintanance to `rabbitmq-dianostics status` and `rabbitmq-dianostics cluster_status`.

**Comment by lukebakken** [comment]
Thanks @michaelklishin . If I have time I may look at adding maintenance status to the management UI somehow.

**Comment by michaelklishin** [comment]
we can start with only adding it to API espouses for 1st GET /api/nodes` and 1st GET /api/nodes/{node}17th

**Comment by coro** [comment]
@michaelklishin does this need to be backported to branch 3.8.x since https://github.com/rabbitmq/rabbitmq-server/issues/2321 is getting backported?

(I came across this while trying to play about with this feature in a 3.8.x-alpha build; apologies if you've a different process I'm not familiar with)

**Comment by michaelklishin** [comment]
@coro it will be backported together with other PRs for `3.8.8`. `3.8.7` will be a security patch release.

**Comment by michaelklishin** [comment]
Backported to `v3.8.x`.

**Pull request merged**
