### PR TITLE
Make shutdown command require the node to be local.

### PR DESCRIPTION
**Pull request by hairyhum**
Shutdown waits for the node to stop based on OS pid,
if the node is not local, the pid file won't be local and will never exist.

[#142699795]

It's not that easy to autotest this feature, because it requires a node on a different host.

### CODE REVIEW

**Comment by michaelklishin** [comment]
I've moved the check to a validator.

**Comment by michaelklishin** [comment]
Let's double check if the BOSH release may be using this in a non-local scenario under any circumstances since it technically does work (the node will stop), even though not really as expected (it won't wait for the pid).

**Comment by michaelklishin** [comment]
@gerhard FYI.

**Comment by michaelklishin** [comment]
I introduced a new flag, `--[no]-wait`, that lets the user shut down remote nodes without waiting for a confirmed termination if she opts in.

**Comment by michaelklishin** [comment]
Backported to `v3.7.x`.

**Comment by gerhard** [comment]
This makes sense, good catch.

I can see that [cf-rabbitmq-release uses shutdown with remote nodes](https://github.com/pivotal-cf/cf-rabbitmq-release/blob/cf3ab586f26051964702a260459c56763f333711/src/rabbitmq-upgrade-preparation/rabbitmqctl/rabbitmqctl.go#L89), this change is likely to impact them. cc @rabbitmq/rabbitmq-pcf-tile-team 

[rabbitmq-server-boshrelease uses shutdown with local node](https://github.com/rabbitmq/rabbitmq-server-boshrelease/blob/98e30b2bfec571ea726e44793f3b6da99c62af1e/jobs/rabbitmq-server/templates/bin/stop#L40), no impact. cc @rabbitmq/sme

**Comment by gerhard** [comment]
We've discovered with @nodo that in [cf-rabbitmq-release](https://github.com/pivotal-cf/cf-rabbitmq-release) `inet_db:gethostname/0` returns `localhost` for all nodes. This results in the remote node check failing, since `hostname == remote_hostname` is always true.  Because [hostnames are resolved via `erl_inetrc`](https://github.com/pivotal-cf/cf-rabbitmq-release/blob/f150692870b74d8ea3248791f29bd46bc4a2c499/jobs/rabbitmq-server/templates/pre-start.bash#L84-L90), the OS cannot resolve RabbitMQ node hostnames - including the local one - which is why the hostname defaults to `localhost` on all nodes.

Should we make the remote node check account for this edge-case?

**Comment by lukebakken** [comment]
If they are both `localhost` we could just print a warning that they're using shutdown in yolo mode :smile:

**Comment by michaelklishin** [comment]
@gerhard if a hostname is `localhost` for all nodes, how can they be distinguished? I would strongly prefer to see this fixed in `cf-rabbitmq-release` over us adding more hacks.

**Comment by lukebakken** [comment]
FWIW this is probably pretty common. Here's what I see on my own workstation -

```
^C(21.2.6)lbakken@shostakovich ~/development/rabbitmq/umbrella (master=)
$ erl
Erlang/OTP 21 [erts-10.2.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Eshell V10.2.4  (abort with ^G)
1> inet_db:gethostname().
"localhost"

(21.2.6)lbakken@shostakovich ~/development/rabbitmq/umbrella (master=)
$ hostname
shostakovich

(21.2.6)lbakken@shostakovich ~/development/rabbitmq/umbrella (master=)
$ hostname -f
localhost.localdomain
```
The startup scripts use `$HOSTNAME` and / or the output of `hostname -f` to set node names, and not `inet_db` which is why this sort of thing doesn't affect RMQ operation normally.

**Comment by gerhard** [comment]
You might be thinking about the value returned in`node()`, and the nodename that gets used for RPC calls. `inet_db:get_hostname()` differs from that.

**Comment by michaelklishin** [comment]
If `inet_db` doesn't take node name or `ERL_INETRC` into account, we should use a different mechanism.

**Comment by gerhard** [comment]
Let me reproduce this issue locally so that it's easier to fix.

**Comment by nodo** [comment]
@gerhard happy to help if you want to.

**Pull request merged**
