### PR TITLE
The command to restart a vhost.

### PR DESCRIPTION
**Pull request by hairyhum**
The command will attempt to restart a vhost.
If restarted successfully, return exit code 0
If the vhost is already started, return exit code 0 and notify that it's already started.
If there is an error restarting, return exit code 70 and the error
Part of rabbitmq/rabbitmq-server#1321
[#149484305]

### CODE REVIEW

**Comment by lukebakken** [comment]
Other than my comment about getting help, restarting vhosts works great -

```
$ ./escript/rabbitmqctl list_vhosts name tracing cluster_state
Listing vhosts ...
foobar  false   [{rabbit@shostakovich, stopped}]
/       false   [{rabbit@shostakovich, running}]

$ ./escript/rabbitmqctl restart_vhost -p foobar
Trying to restart vhost 'foobar' on node 'rabbit@shostakovich' ...
Successfully restarted vhost 'foobar' on node 'rabbit@shostakovich'

$ ./escript/rabbitmqctl list_vhosts name tracing cluster_state
Listing vhosts ...
foobar  false   [{rabbit@shostakovich, running}]
/       false   [{rabbit@shostakovich, running}]
```

**Comment by michaelklishin** [comment]
@lukebakken how about now?

**Comment by lukebakken** [comment]
Let me double-check with the other vhost commands

**Comment by lukebakken** [comment]
@michaelklishin :shipit:

**Pull request merged**
