### PR TITLE
Add rabbit module to TEST_DEPS

### LINKED ISSUE #222: Remove dependency on "rabbit" application
See [this comment](https://github.com/rabbitmq/rabbitmq-cli/pull/221#pullrequestreview-65773309) and its discussion.

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #222

### CODE REVIEW

**Comment by hairyhum** [comment]
`def validate([],  %{pid: _} = opts), do: Validators.rabbit_is_loaded([], opts)` validator makes sire rabbit code is loaded (from `RABBITMQ_HOME`). We use this trick in several commands to avoid circular dependencies, while we still need rabbit code, for example in plugins. Do you think we should move all functions used by CLI to `rabbit_common`?

**Comment by michaelklishin** [comment]
@hairyhum we rely on `rabbit_plugins` only in `rabbitmq-plugins`, is there anything else? If it's a single module, perhaps it's worth moving?

**Comment by hairyhum** [comment]
We use it in plugins commands, `hipe_compile`, `forget_cluster_node`, `rename_cluster_node`, `wait` and command discovery (for plugins commands). Everything that uses `Validators.rabbit_is_loaded` or `Helpers.require_rabbit`

**Comment by michaelklishin** [comment]
@hairyhum I'm inclined to say that things should stay the way they are. We tried to make `rabbit-common` smaller before and there's interest in not letting it grow if we can help it. WDYT?

**Comment by hairyhum** [comment]
I think the problem here is a circular dependency in the build system. While there is no circular dependency in the executable code (rabbit code does not use cli). So I don't think moving everything to common is the right way to solve it.

**Comment by lukebakken** [comment]
OK, I can just add `rabbit` to `TEST_DEPS`.

**Comment by lukebakken** [comment]
@michaelklishin @hairyhum all set

**Pull request merged**
