### PR TITLE
Add a flag to cipher_suites command to get all ciphers. Add --format flag to select format. Remove openssl_format flag

### PR DESCRIPTION
**Pull request by hairyhum**
Support new map format for cipher suites added in OTP-20.3
Support `--all` flag to get all available ciphers

Addresses #342
Depends on changes in rabbitmq-server https://github.com/rabbitmq/rabbitmq-server/pull/1991

### CODE REVIEW

**Comment by hairyhum** [comment]
It feels like formats would be cleaner if there is a single string flag e.g. `--format=openssl`
We may leave `--openssl-format || --erlang-format` options and remove them in 3.8

**Comment by michaelklishin** [comment]
We can keep them and make them delegate to `--format=…` ;)

**Comment by hairyhum** [comment]
I'm not sure how keeping them and adding a new flag makes things better.

**Comment by michaelklishin** [comment]
Only for backwards compatibility. We will remove them from the docs.

**Comment by hairyhum** [comment]
By the way, `erlang_format` was only added in master and `openssl_format` was made default in master. I'm not sure if that's on purpose, but I'm leaning towards moving to `--format` flag and removing `--erlang-format` before it's released.

**Comment by hairyhum** [comment]
I'm going to submit another PR for 3.7

**Comment by michaelklishin** [comment]
The default change for 3.8 was intentional.

**Pull request merged**
