### PR TITLE
Handle offline remote node in rename_cluster_node

### PR DESCRIPTION
**Pull request by lukebakken**
If the value for `mnesia_dir` or `feature_flags_file` comes back `undefined` we need to try again in offline mode.

#457

### CODE REVIEW

**Comment by lukebakken** [comment]
@dumbbell note that this isn't enough to fix #457. With this patch applied, you will see the following error:

```
(23.1.1)lbakken@shostakovich ~/development/rabbitmq/umbrella/deps/rabbitmq_cli (rabbitmq-cli-457=)
$ ERL_LIBS=../rabbitmq_server_release/plugins ./escript/rabbitmqctl rename_cluster_node rabbit@shostakovich rabbit@rabbit_fixedhost
Renaming cluster nodes: 
 rabbit@shostakovich -> rabbit@rabbit_fixedhost 

Error:
{:rename_failed, {:badmatch, {:error, :enoent}}}
```

I started trying to track down where `enoent` is returned here, but this isn't the correct place and I have run out of time today -

```
(23.1.1)lbakken@shostakovich ~/development/rabbitmq/umbrella/deps/rabbit (master *=)
$ git diff
diff --git a/src/rabbit_mnesia_rename.erl b/src/rabbit_mnesia_rename.erl
index e0d88c0f5..f4a5efa79 100644
--- a/src/rabbit_mnesia_rename.erl
+++ b/src/rabbit_mnesia_rename.erl
@@ -61,8 +61,14 @@ rename(Node, NodeMapList) ->
         become(FromNode),
         take_backup(before_backup_name()),
         convert_backup(NodeMap, before_backup_name(), after_backup_name()),
-        ok = rabbit_file:write_term_file(rename_config_name(),
-                                         [{FromNode, ToNode}]),
+        Rcn = rename_config_name(),
+        io:format(standard_error, "@@@@@@@@ rabbit_file:write_term_file Rcn: ~p FromNode: ~p ToNode: ~p~n", [Rcn, FromNode, ToNode]),
+        ok = case rabbit_file:write_term_file(Rcn, [{FromNode, ToNode}]) of
+            ok -> ok;
+            Error ->
+                io:format(standard_error, "@@@@@@@@ Error: ~p~n", [Error]),
+                Error
+        end,
         convert_config_files(NodeMap),
         become(ToNode),
         restore_backup(after_backup_name()),
```

**Comment by lukebakken** [comment]
@dumbbell this appears to fix the issue. If you're testing the fix using `deps/rabbitmq_server_release/sbin/rabbitmqctl` in the umbrella, you'll have to set an env var:

```
RABBITMQ_MNESIA_BASE="/tmp/rabbitmq-test-instances/rabbit@shostakovich/mnesia" ./sbin/rabbitmqctl rename_cluster_node rabbit@shostakovich rabbit@rabbit_fixedhost
```

**Review by dumbbell — CHANGES_REQUESTED** [review]
The CLI testsuite does not pass with the change. At least the following assertion:
https://github.com/rabbitmq/rabbitmq-cli/blob/e68db684cc5dd6debfdca276adfcf0014127cf3a/test/ctl/rename_cluster_node_command_test.exs#L65-L66

Also, I think a more appropriate commit message would say that if the remote node is unavailable, we use the default values of `mnesia_dir` and `feature_flags_file`.

**Comment by lukebakken** [comment]
Great I forgot to run the tests 🙄 that reminds me to look into how `rename_cluster_node` is tested anyway.

**Comment by dumbbell** [comment]
I pushed fixes to the testsuite. By fixes, I mean I removed assertions testing the old behavior. The other failures I had were unrelated (testcases not cleaning up their changes, which meant the testsuite couldn't be executed twice in a row, and Elixir compiler crashing).

In another commit, I updated the Travis configuration so we get relevant feedback from CI.

**Comment by lukebakken** [comment]
OK I was just about to push my changes :stuck_out_tongue:

**Review by dumbbell — APPROVED** [review]

**Comment by dumbbell** [comment]
I believe the change is ready. What do you think?

**Comment by lukebakken** [comment]
Yep! I'll get it. I just had some food.

**Comment by lukebakken** [comment]
Backported to `v3.8.x`

**Comment by lukebakken** [comment]
I built a generic-unix package and verified this fix - `rabbitmq_server-3.8.0+rc.1.60.g7dabdd1`. I did so because of this follow-up message: https://groups.google.com/d/msg/rabbitmq-users/LZCh9n-LuZM/pMMA8BchCwAJ

I'm going to test to see if my workaround can actually work for this user.

**Pull request merged**
